version: "2"
services:
  web:
    build:
      context: .
    command: gunicorn kitchensink.app:create_app\(\) -w 3 -b 0.0.0.0:9000 -k gevent
    labels:
      - convox.port.443.protocol=https
    ports:
    - 80:9000
    - 443:9000